// <auto-generated />
using Discussion.Core.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Discussion.Web.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    partial class BaseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Discussion.Core.Database.Entities.Comment.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("HeadCommentId")
                        .HasColumnType("integer")
                        .HasColumnName("head_comment_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("HeadCommentId")
                        .HasDatabaseName("ix_comments_head_comment_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_comments_user_id");

                    b.ToTable("comments");
                });

            modelBuilder.Entity("Discussion.Core.Database.Entities.Comment.CommentFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommentId")
                        .HasColumnType("integer")
                        .HasColumnName("comment_id");

                    b.Property<int>("FileId")
                        .HasColumnType("integer")
                        .HasColumnName("file_id");

                    b.Property<int>("StorageItemId")
                        .HasColumnType("integer")
                        .HasColumnName("storage_item_id");

                    b.HasKey("Id")
                        .HasName("pk_comment_files");

                    b.HasIndex("CommentId")
                        .HasDatabaseName("ix_comment_files_comment_id");

                    b.HasIndex("StorageItemId")
                        .HasDatabaseName("ix_comment_files_storage_item_id");

                    b.ToTable("comment_files");
                });

            modelBuilder.Entity("Discussion.Core.Database.Entities.Comment.CommentImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommentId")
                        .HasColumnType("integer")
                        .HasColumnName("comment_id");

                    b.Property<int>("FileId")
                        .HasColumnType("integer")
                        .HasColumnName("file_id");

                    b.Property<int>("StorageItemId")
                        .HasColumnType("integer")
                        .HasColumnName("storage_item_id");

                    b.HasKey("Id")
                        .HasName("pk_comment_images");

                    b.HasIndex("CommentId")
                        .HasDatabaseName("ix_comment_images_comment_id");

                    b.HasIndex("StorageItemId")
                        .HasDatabaseName("ix_comment_images_storage_item_id");

                    b.ToTable("comment_images");
                });

            modelBuilder.Entity("Discussion.Core.Database.Entities.Storage.StorageItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("extension");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_name");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("storage_path");

                    b.HasKey("Id")
                        .HasName("pk_storage_items");

                    b.HasIndex("StoragePath")
                        .IsUnique()
                        .HasDatabaseName("ix_storage_items_storage_path");

                    b.ToTable("storage_items");
                });

            modelBuilder.Entity("Discussion.Core.Database.Entities.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("ix_user_user_name");

                    b.ToTable("user");
                });

            modelBuilder.Entity("Discussion.Core.Database.Entities.Comment.Comment", b =>
                {
                    b.HasOne("Discussion.Core.Database.Entities.Comment.Comment", "HeadComment")
                        .WithMany("ReplyComments")
                        .HasForeignKey("HeadCommentId")
                        .HasConstraintName("fk_comments_comments_head_comment_id");

                    b.HasOne("Discussion.Core.Database.Entities.User.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_user_user_id");

                    b.Navigation("HeadComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Discussion.Core.Database.Entities.Comment.CommentFile", b =>
                {
                    b.HasOne("Discussion.Core.Database.Entities.Comment.Comment", "Comment")
                        .WithMany("Files")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_files_comments_comment_id");

                    b.HasOne("Discussion.Core.Database.Entities.Storage.StorageItem", "StorageItem")
                        .WithMany()
                        .HasForeignKey("StorageItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_files_storage_items_storage_item_id");

                    b.Navigation("Comment");

                    b.Navigation("StorageItem");
                });

            modelBuilder.Entity("Discussion.Core.Database.Entities.Comment.CommentImage", b =>
                {
                    b.HasOne("Discussion.Core.Database.Entities.Comment.Comment", "Comment")
                        .WithMany("Images")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_images_comments_comment_id");

                    b.HasOne("Discussion.Core.Database.Entities.Storage.StorageItem", "StorageItem")
                        .WithMany()
                        .HasForeignKey("StorageItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_images_storage_items_storage_item_id");

                    b.Navigation("Comment");

                    b.Navigation("StorageItem");
                });

            modelBuilder.Entity("Discussion.Core.Database.Entities.Comment.Comment", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Images");

                    b.Navigation("ReplyComments");
                });

            modelBuilder.Entity("Discussion.Core.Database.Entities.User.User", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
